version: '3.8'

services:
  uiux-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uiux-bot-ts
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./images:/app/images:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kolkata
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "node", "dist/scripts/health-check.js"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 